=== idksoftware/samonitor/sam/config/groups.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Groups">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Group">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" />
              <xs:element name="GID" type="xs:string" />
              <xs:element name="GroupList">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="User" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== idksoftware/samonitor/sam/config/groups.xml
<?xml version="1.0" encoding="UTF-8"?>
<Groups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation=".\groups.xsd">
	<Group>
		<Name>test1</Name>
		<GID>100</GID>
		<GroupList>
			<User>Iain</User>
		</GroupList>
	</Group>
	<Group>
		<Name>test2</Name>
		<GID>101</GID>
		<GroupList>
			<User>Iain</User>
		</GroupList>
</Group>
	<Group>
		<Name>test3</Name>
		<GID>102</GID>
		<GroupList>
			<User>Iain</User>
		</GroupList>
</Group>
	<Group>
		<Name>test4</Name>
		<GID>103</GID>
		<GroupList>
			<User>Iain</User>
		</GroupList>
	</Group>
	<Group>
		<Name>test5</Name>
		<GID>104</GID>
		<GroupList>
			<User>Iain</User>
		</GroupList>
	</Group>
</Groups>
