=== idksoftware/samonitor/sam/config/machines.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Machines">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Machine">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="HostName" type="xs:string" />
              <xs:element name="Address" type="xs:string" />
              <xs:element name="Trys" type="xs:unsignedByte" />
              <xs:element name="Delay" type="xs:unsignedByte" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== idksoftware/samonitor/sam/config/machines.xml
<?xml version="1.0" encoding="UTF-8"?>
<Machines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\machines.xsd">
	<Machine>Fred's machine
		<HostName>NAIW1414J2J</HostName>
		<Address>3.27.251.144</Address>
		<Trys>4</Trys>
		<Delay>60</Delay>
	</Machine>
	<Machine>Iain's machine
		<HostName>NAIW1414J2J</HostName>
		<Address>3.27.251.97</Address>
		<Trys>4</Trys>
		<Delay>60</Delay>
	</Machine>
	<Machine>Email Server
		<HostName>NAIW1414J2J</HostName>
		<Address>3.27.251.97</Address>
		<Trys>4</Trys>
		<Delay>60</Delay>
	</Machine>
	<Machine>Pop3 Server
		<HostName>NAIW1414J2J</HostName>
		<Address>3.27.251.97</Address>
		<Trys>4</Trys>
		<Delay>60</Delay>
	</Machine>
	<Machine>Pop3 Server
		<HostName>NAIW1414J2J</HostName>
		<Address>3.27.251.97</Address>
		<Trys>4</Trys>
		<Delay>60</Delay>
	</Machine>
</Machines>
